### ISSUE TITLE
Inconsistent number of results

### ISSUE THREAD

**Issue by sdfordham** [AnthonyBloomer/daftlistings#102]
Related to (#101) the following code:
````python
from daftlistings.daft import Daft
from daftlistings.enums import SearchType, PropertyType, Ber
from daftlistings.location import Location

daft = Daft()
daft.set_search_type(SearchType.RESIDENTIAL_RENT)
daft.set_property_type(PropertyType.APARTMENT)
daft.set_property_type(PropertyType.HOUSE)
daft.set_location("Galway")
daft.set_min_beds(1)
daft.set_max_beds(2)
daft.set_min_price(1500)
daft.set_max_price(2000)

listings = daft.search(max_pages=4)
print(len(listings))
````
_Usually_ gives output:
````console
Got 1477 results.
200
````
but annoyingly sometimes:
````console
Got 1477 results.
177
````

**Comment by AnthonyBloomer** [comment]
The logic seems fine. Is it always 177 or some other number? Perhaps some properties were removed during your testing.

**Comment by sdfordham** [comment]
`PAGE_SZ=50` so the 'last' page should have 27 results, but it looks like sometimes this last page is actually the first page so we get 27 + 50 + 50 + 50 results instead of 50 + 50 + 50 + 50 results. Looking at the daft website, this doesnt seem to really matter since they are using infinite scrolling. But I could be missing something here.

**Comment by AnthonyBloomer** [comment]
I couldn't replicate this. Perhaps explicity setting the sort type may fix it. That's all I can really think of at the moment. It may be a problem with Daft's API 😄
