### ISSUE TITLE
PropertyType SearchType combos

### ISSUE THREAD

**Issue by sdfordham** [AnthonyBloomer/daftlistings#108]
Need logic to compare `PropertyType` and `SearchType`, empirically seems can only use `APARTMENT`, `STUDIO_APARTMENT` or `HOUSE` (or no searchtype string) with `SearchType.RESIDENTIAL_RENT` but any option is okay with the buy type options. This apparently matches the selectable options on the website.

**Comment by AnthonyBloomer** [comment]
Something like this? 

```python
def set_property_type(self, property_type: PropertyType):
    if not isinstance(property_type, PropertyType):
        raise TypeError("Argument must be enums.PropertyType.")
    if self._section and self._section == "residential-for-sale":
        if property_type.value not in ["apartments", "studio-apartments", "houses"]:
            raise TypeError(
                "PropertyType should be APARTMENT, STUDIO_APARTMENT, or HOUSE."
            )
    self._add_filter("propertyType", property_type.value)
```

**Comment by EricNeville** [comment]
Wouldn't it also make sense to raise some error if self._section has not yet been set and require it to be set first? Otherwise we can still have `SearchType.RESIDENTIAL_RENT` with an incompatible `PropertyType` by setting them in the opposite order.
