### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by meagher43** [AnthonyBloomer/daftlistings#169]
Hi,

I am using daftlistings version 2.0.2 and when I follow the steps in the ReadMe I get a JSONDecodeError.

I've attached an image with the reproduction steps.
![image](https://github.com/AnthonyBloomer/daftlistings/assets/6528531/8b4e0c06-41bd-4d10-a7a9-7c5f3c650e10)
![image](https://github.com/AnthonyBloomer/daftlistings/assets/6528531/3301d554-6159-4735-9c78-fefe05c9bf49)

**Comment by sdfordham** [comment]
You will need to install the latest version of this package 2.0.4 it is on PyPI. Daft changed the API endpoint recently which broke the package, the new version is working.

**Comment by meagher43** [comment]
Got it, I thought I had upgraded but hadn't, thanks Anthony!
