### ISSUE TITLE
set_added_since is ineffective

### ISSUE THREAD

**Issue by GianlucaFicarelli** [AnthonyBloomer/daftlistings#29]
The method set_added_since in the Daft class is ineffective.
To fix it, it's enough to replace:
`self._query_params + str(QueryParam.DAYS_OLD) + str(added)`
with:
`self._query_params += str(QueryParam.DAYS_OLD) + str(added)`

**Comment by AnthonyBloomer** [comment]
Hi @GianlucaFicarelli, thanks for raising this issue. I will add the fix in the next release.
