### ISSUE TITLE
request: make as_dict process values asynchronously

### ISSUE THREAD

**Issue by Munzey** [AnthonyBloomer/daftlistings#33]
thanks for replying to my other requests! really cool api you made. Planning to use it in a demo mobile app ( which will probably remain a demo due to [Daft's TOS](https://www.daft.ie/legal#restrictions) 😬 )

I wanted to make a server which would basically act as a rest api for daft using your api.  When jsonifying the listing objects, I need to convert to `as_dict` first. A big performance boost here would be if [`as_dict`](https://github.com/AnthonyBloomer/daftlistings/blob/master/daftlistings/listing.py#L419) resolved each value from daft asynchronously.

i guess you could use python 3.5.+ `await/async` syntax, or to keep it python 2/3 agnostic [gevent](https://pypi.org/project/gevent/) seems to work

**Comment by AnthonyBloomer** [comment]
Hi @Munzey, that's a great suggestion. I was actually thinking of doing this a while back. I'll have a look into gevent at some stage this week.
