### ISSUE TITLE
No Listings 

### ISSUE THREAD

**Issue by mickdaly** [AnthonyBloomer/daftlistings#53]
Nice script.

Some filters produce listings but searching for houses does not, e.g.

```
daft = Daft()
daft.set_result_url("https://www.daft.ie/cavan/houses-for-sale/?ad_type=sale&advanced=1&s%5Bmnb%5D=4&s%5Bmnbt%5D=3&s%5Badvanced%5D=1&searchSource=sale")

listings = daft.search()
```

Additionally, no listings are returned when using `SaleType.HOUSES` instead of `set_result_url`.

**Comment by AnthonyBloomer** [comment]
Hi @mickdaly,

Daft.ie have started moving their frontend to React so a lot of this library is currently broken. 

There's a new development branch which you can clone:
>http://github.com/AnthonyBloomer/daftlistings/tree/daft-property-for-sale 

That branch includes fixes to get basic property for sale data including price, url and address.

I'll close this issue as it is related to: https://github.com/AnthonyBloomer/daftlistings/issues/45
