### ISSUE TITLE
Contact_advertiser doesn't give copy of email sent

### ISSUE THREAD

**Issue by evanjmg** [AnthonyBloomer/daftlistings#55]
This may be a feature request but is this is standard on the daft site. I'm assuming contact advertiser does the same thing as email correct? And that there is a flag for getting a copy of the email sent? - To confirm it was sent correctly.

**Comment by AnthonyBloomer** [comment]
Hello @evanjmg! Great question. The `contact_advertiser` method uses the contact form on a listing page. The checkbox is only visible to logged in users. I checked the page source and found the name of the checkbox is `self_copy`. I updated the payload with `'self_copy' : 1` and this will now send you a copy to confirm it was sent successfully. :)

**Comment by evanjmg** [comment]
Thank you so much!

**Comment by evanjmg** [comment]
Is there a new pip version for this?

**Comment by AnthonyBloomer** [comment]
Yes, I just pushed `1.7.2` to PyPi. Enjoy! 👍
