### ISSUE TITLE
Latitude & Longitude returning `None`

### ISSUE THREAD

**Issue by pbuckley4192** [AnthonyBloomer/daftlistings#57]
Hey,

I was writing a script today to siphon off all of the houses in Cork into a Google MyMaps (just find it easier that way)

I noticed that the script returned None for both Latitude and Longitude... :(

I installed the module via `pip install daftlistings`

Example link to error case:

https://www.daft.ie/cork/studio-apartments-for-rent/kinsale/10-hillcre-kinsale-cork-1962386/

Exerpt from the page showing the data does exist
```
$(function() {
            if (typeof trackingParam === 'undefined') {
                var trackingParam = {"environment":"prod","platform":"desktop","page_name":"PropertyDetails","area":"Kinsale","county":"Cork","longitude":-8.5363374,"latitude":51.7095033,"seller_type":"private","property_category":"rental","ad_id":"21962386","property_title":"10 hillcre, Kinsale, Co. Cork","published_date":"2019-09-02","no_of_photos":8,"currency":"\u20ac","price_frequency":"monthly","price":1000,"bathrooms":0,"beds":0,"facility":"Parking,Central Heating,Washing Machine,Dryer,Microwave,Internet,Garden \/ Patio \/ Balcony,Serviced Property","open_viewing":"no","available_from":"2019-10-01","property_type":"studio","ad_ids":"21962227,21951003,21955972,21960146,21957792,21935650,21957202,21961035","available_for":"6","furnished":"yes","lease_units":"months"};
                tealiumTrack(577634, 4, 'PropertyDetails', trackingParam);
            }
        });
```

Minor snippet of code I used..
```
print(listing.latitude)
print(listing.longitude)
```

I had a look at the code and I see there is a regex in use; is it possible the page's code has changed?

**Comment by sdfordham** [comment]
The code looks for latitude and longitude in the scripts section and finds nothing so it returns nothing. If you look in scripts the coordinate data appears to be in `.setLngLat`.
