### ISSUE TITLE
daft.search() returns number of results on page, not number of search results

### ISSUE THREAD

**Issue by sdfordham** [AnthonyBloomer/daftlistings#61]
After e.g.

>from daftlistings import Daft, RentType
>
>daft = Daft()
>
>daft.set_county("Dublin City")
>daft.set_listing_type(RentType.APARTMENTS)
>daft.set_min_price(1000)
>daft.set_max_price(1500)
>
>listings = daft.search()

The output is

>Found 20 items

But after checking `daft.get_url()` the search actually found 84 results, the 20 refers to the number of results on the first page, gotten by counting `<div>`s in the url. Is there a way to get *all* results? As far as I can see there isn't but I guess it's possible either 1.) use `daft.offset()` to iterate through pages until you get less than 20 `<div>`s on a page, or 2.) regex'ing for "Found XXX properties" in the returned url. Not sure which is preferable here, I guess the former.

**Comment by AnthonyBloomer** [comment]
Hi @sdfordham, good spot. I think that print should be removed. In terms of getting the total number of properties, I'm thinking the regex method would be the quickest way to get the total number rather than having to iterate over each page to get the total count.

**Comment by AnthonyBloomer** [comment]
I added a new method `search_count` to the Daft class that returns the total number of properties. 

Example usage:

``` python
from daftlistings import Daft, RentType

daft = Daft()
daft.set_listing_type(RentType.APARTMENT_TO_SHARE)

listings = daft.search()

print(daft.search_count)
```

**Comment by sdfordham** [comment]
I guess I was indirectly considering the following: if a user does `listings = daft.search()` then what should the result of that be? At the moment it puts 20 results into `listings` (or however many appear on page 1 of the search) but that seems kinda arbitrary. Should `listings = daft.search()` get back all the results into listings?

**Comment by AnthonyBloomer** [comment]
@sdfordham, you can use the [`offset` method](https://github.com/AnthonyBloomer/daftlistings/blob/dev/daftlistings/daft.py#L170) to increment the page number and iterate over each page. Having the `search_count` allows you to work out what that offset should be. However, I do like the idea of having the search method automatically get all listings. Perhaps this could be added as an optional param to the search method i.e (`search(fetch_all=True`)?

**Comment by AnthonyBloomer** [comment]
I'll close this issue and  use #62 for further discussion.
