### ISSUE TITLE
fetch_all arg for search()

### ISSUE THREAD

**Issue by sdfordham** [AnthonyBloomer/daftlistings#62]
Referring to end of #61.

**Comment by AnthonyBloomer** [comment]
Hi @sdfordham, thanks for opening this issue! I've put together something which addresses this in the commit referenced above. Let's discuss if there's anything we can add/change with this approach.

**Comment by sdfordham** [comment]
I think that commit closes this. It's still not clear to me whether it should be `fetch_all=True` or  `fetch_all=False` by default. Probably the `False` option is better for now.

**Comment by AnthonyBloomer** [comment]
Yeah I've mixed opinions on that myself. I'm thinking If the user makes a search they're going to want all listings by default. Anyway I'll update the documentation with the new usage info so users know the feature is there and I'll push a new version to PyPi tomorrow. I'll go ahead and close this issue. Thanks for contributing with ideas to improve this project, it's really appreciated!
