### ISSUE TITLE
Store price_integer on location?

### ISSUE THREAD

**Issue by Jack-Collins** [AnthonyBloomer/daftlistings#64]
Does this make sense to add? Would be handier than having to extract the integer from the string every time.

**Comment by AnthonyBloomer** [comment]
Hi Jack, are you referring to the price function in listings.py?

**Comment by Jack-Collins** [comment]
Yep, the price property. It returns something like `€200,000` and you currently need to parse out the commas and currency symbol for numerical analysis.

Very useful package by the way!

**Comment by AnthonyBloomer** [comment]
@Jack-Collins, thanks for the feedback! 👍That makes sense. I'm sure the majority of use-cases with this library would involve parsing the price value. I've updated the price method which you can see referenced above. If the properties are let per week then I mutiply the value by 4.345 to get an approximate result. I hope that helps!
