### ISSUE TITLE
Please update the url.py example to work without pagination

### ISSUE THREAD

**Issue by vladola** [AnthonyBloomer/daftlistings#65]
Hey there!

First, I immensely appreciate the work you put into this :). I just wanted to mention something as somebody might have my same "problem".

In my app I followed [this example](https://github.com/AnthonyBloomer/daftlistings/blob/dev/examples/url.py) to go through all the results.

What I found is that I kept getting duplicate listing objects all over the place. After some trial and error I figured that the manual offset is no longer necessary as the `search()` function now has the `fetch_all=True` option and automatically fetches everything in one swoop.

https://github.com/AnthonyBloomer/daftlistings/blob/2cb90b585cb01cffe86ad0bea04dc03682dfb3a6/daftlistings/daft.py#L434

This is just to avoid somebody else the headache :).

Thanks and happy Christmas 🎄

**Comment by AnthonyBloomer** [comment]
Thanks for raising this issue! I'll get that example updated. I think it'd be a good idea to also update the README documenting the `fetch_all` feature.
