### ISSUE TITLE
exporting to xlsx

### ISSUE THREAD

**Issue by alexnorwood01** [AnthonyBloomer/daftlistings#68]
hi, 
New to python but your daft listings has been a great help. Only thing is that i'm struggling with is to get the list results into a dataframe. Any help greatly received. 

Thanks, Alex
[daft.xlsx](https://github.com/AnthonyBloomer/daftlistings/files/4330542/daft.xlsx)

**Comment by AnthonyBloomer** [comment]
Hey @alexnorwood01, check out #71.
