### ISSUE TITLE
When getting the price of the property to rent, the price method of PropertyForSale class is invoked

### ISSUE THREAD

**Issue by YifeiLuDublin** [AnthonyBloomer/daftlistings#72]
Hi Anthony,

I was using your crawler to build a [renting properties visualision](http://yifei.lu/dublin_apartment_to_rent_2_bed_price_map.html). And I can't tell the difference between weekly and monthly prices of the crawled listings. After adding print("calling property for sale") to PropertyForSale class's price method, I found out that this method was called rather than PropertyForRent's price method.

Below is a simple script to run after you adding the print statement:

`from daftlistings import Daft, RentType, Listing

daft = Daft()
daft.set_county("Dublin City")
daft.set_listing_type(RentType.ANY)
daft.set_min_price(330)
daft.set_max_price(4000)
daft.set_min_beds(4)
daft.set_max_beds(4)

listings = daft.search()

for listing in listings:
    listing.price`

Thanks,
Yifei

**Comment by AnthonyBloomer** [comment]
Hello @YifeiLuDublin, 

That's a cool visualization. Thank you for creating this issue. I've updated the code to check if `listing_type` is an instance of `RentType`. If it is I create a list of `PropertyForRent` objects.
