### ISSUE TITLE
ImportError: cannot import name 'MapVisualization'

### ISSUE THREAD

**Issue by yashkarle** [AnthonyBloomer/daftlistings#76]
trying to import as following which gives the error for MapVisualization:
`from daftlistings import Daft, RentType, SortOrder, SortType, MapVisualization`

Mac jupyter notebook: /anaconda3/lib/python3.6/site-packages (1.8.0)

**Comment by AnthonyBloomer** [comment]
Hello @yashkarle, thank you for creating this issue!

I've published the latest version to PyPi which includes the `MapVisualization` class:

https://pypi.org/project/daftlistings/1.8.1/

You can install it using pip:

```
pip install daftlistings==1.8.1
```

**Comment by yashkarle** [comment]
thanks @AnthonyBloomer 
I could now import `MapVisualization`
