### ISSUE TITLE
Fetched 0 listings.

### ISSUE THREAD

**Issue by Jack-Collins** [AnthonyBloomer/daftlistings#81]
When I try the example:
```
from daftlistings import Daft

daft = Daft()
listings = daft.search()

for listing in listings:
    print(listing.formalised_address)
    print(listing.daft_link)
    print(listing.price)
```

I get no listings:

````
http://www.daft.ie/ireland/property-for-sale/?offset=0
Fetched 0 listings.
````

Is the scraper broken? (I'm on daftlistings-1.8.1-py2.py3-none-any.whl)]]

Thanks

**Comment by TheJokersThief** [comment]
The site's design was updated last week so unfortunately things don't work at the moment :(

If you want to, the new design dumps a bunch of JSON data about the data that [you can parse](https://github.com/AnthonyBloomer/daftlistings/issues/80#issue-753721710) with something like:


```
script_text = self._ad_page_content.find('script', {'id': '__NEXT_DATA__'})
json.loads(script_text.string)
```

If you want to look into it more, I did something similar here: https://github.com/TheJokersThief/daft-scraper/blob/main/daft_scraper/search/__init__.py#L71-L74

I think it'd be easy enough to use that data and align the daftlistings library with the new design :)

**Comment by Jack-Collins** [comment]
Thanks @TheJokersThief, that worked great!
