### ISSUE TITLE
does the lib still works with new Daft UI

### ISSUE THREAD

**Issue by linhdang** [AnthonyBloomer/daftlistings#82]
Just review the code and it seems to look for div with class PropertyCardContainer__container which is no longer available on the Daft UI. 

Do you have plan to update the library?

**Comment by ahanway** [comment]
Why was this closed? Is the issue resolved?

**Comment by linhdang** [comment]
Nope. But I read your NCI's paper and realise the library is from 2016 and only works with the Daft UI back then.

**Comment by goodshort** [comment]
It worked until at least end of November (see [here] (https://www.goodshort.me/projects/daftlinstings-galway)). Not sure exactly when daft decided to change UI.
It doesn't look like the search urls changed much. If I have some time I might clone and send a PR, but I guess for now, this issue can remain open as it is actually an ongoing issue.

**Comment by linhdang** [comment]
I'm managed to pull Daft's data via 
```
 r = requests.post('https://search-gateway.dsch.ie/v1/listings', headers={
            "Content-Type": "application/json",
            "brand": "daft",
            "platform": "web"
        }, json={
            "section": section,
            "filters": [
                {
                    "name": "adState",
                    "values": [
                        "published"
                    ]
                }
            ],
            "andFilters": [],
            "ranges": [],
            "paging": {
                "from": from_result,
                "pageSize": page_size
            },
            "terms": ""
        }, )
```

**Comment by sdfordham** [comment]
See #80. The package needs an overhaul after their last update but most of the parsing aspect is now redundant because of the json dump.

**Comment by YifeiLuDublin** [comment]
> I'm managed to pull Daft's data via
> 
> ```
>  r = requests.post('https://search-gateway.dsch.ie/v1/listings', headers={
>             "Content-Type": "application/json",
>             "brand": "daft",
>             "platform": "web"
>         }, json={
>             "section": section,
>             "filters": [
>                 {
>                     "name": "adState",
>                     "values": [
>                         "published"
>                     ]
>                 }
>             ],
>             "andFilters": [],
>             "ranges": [],
>             "paging": {
>                 "from": from_result,
>                 "pageSize": page_size
>             },
>             "terms": ""
>         }, )
> ```

Just a quick question. Is your pull request on Daft's data an API request? If so, does it require an API key from Daft side. Their API documentation page is very confusing.
http://api.daft.ie/doc/v3
"""
Authentication
Each request to the API must be accompanied by an "API key". These keys are in the form of a hex string, not more than 40 characters in length.
"""

**Comment by AnthonyBloomer** [comment]
@YifeiLuDublin, making requests to that service doesn't require an API key. It must be their internal API.

**Comment by YifeiLuDublin** [comment]
> @YifeiLuDublin, making requests to that service doesn't require an API key. It must be their internal API.

Did we just spot a security flow? haha

**Comment by goodshort** [comment]
> > @YifeiLuDublin, making requests to that service doesn't require an API key. It must be their internal API.
> 
> Did we just spot a security flaw? haha

It doesn’t use the daft API, it reads the webpages and pull the data.

**Comment by linhdang** [comment]
> > @YifeiLuDublin, making requests to that service doesn't require an API key. It must be their internal API.
> 
> Did we just spot a security flaw? haha

I think it's the API they are using for website, their site is a public site though so I don't think it's a security flaw. You would need an API key if you want to have better QoS. Without API key, your request might be throttled

**Comment by YifeiLuDublin** [comment]
> I think it's the API they are using for website, their site is a public site though so I don't think it's a security flaw. You would need an API key if you want to have better QoS. Without API key, your request might be throttled

You can pull every daft customer's name, phone, address through this public API with little effort. It can potentially cause a GDPR breach.
