### ISSUE TITLE
Fetched 0 listings

### ISSUE THREAD

**Issue by leej3** [AnthonyBloomer/daftlistings#83]
Great project! Thanks for sharing. Regardless of the query I currently only see the url for the REST api and "Fetched 0 listings". Any thoughts on why this might be?

My current guesses are:
+ Silliness on my part
+ A daft.ie API change
+ some authentication required that I don't know about

Any help would be much appreciated.

An example of what I am running (with a dev install from master):
```
from daftlistings import Daft, SortOrder, SortType, SaleType, MapVisualization
import pandas as pd

daft = Daft()
daft.set_county("Dublin")
daft.set_sort_by(SortType.PRICE)
# must sort by price in asending order, MapVisualization class will take care of the weekly/monthly value mess
daft.set_min_price(400000)
daft.set_max_price(800000)
listings = daft.search(fetch_all=True)

```

**Comment by AnthonyBloomer** [comment]
Hello @leej3, daft.ie updated their site recently which broke this library. I've been busy lately so haven't had time to fix this. I do intend to look into it soon. In the meantime, I would recommend checking out [daft-scraper](https://github.com/TheJokersThief/daft-scraper) which is a similar project to this and works with the new Daft website. Hope that helps!

**Comment by leej3** [comment]
Thanks. Some quirks in the python API but overall daft-scraper worked very nicely.

**Comment by sdfordham** [comment]
> 
> 
> Hello @leej3, daft.ie updated their site recently which broke this library. I've been busy lately so haven't had time to fix this. I do intend to look into it soon. In the meantime, I would recommend checking out [daft-scraper](https://github.com/TheJokersThief/daft-scraper) which is a similar project to this and works with the new Daft website. Hope that helps!

Similar is an understatement, one wonders why the creator didn't just fork and fix this lib.

**Comment by YifeiLuDublin** [comment]
> > Hello @leej3, daft.ie updated their site recently which broke this library. I've been busy lately so haven't had time to fix this. I do intend to look into it soon. In the meantime, I would recommend checking out [daft-scraper](https://github.com/TheJokersThief/daft-scraper) which is a similar project to this and works with the new Daft website. Hope that helps!
> 
> Similar is an understatement, one wonders why the creator didn't just fork and fix this lib.

I tried fixed this lib for solid two days. And I reckon daft-scraper just covers rent properties while this lib covers all sorts of properties on daft.ie. Just covering rent properties reduces the complexity.

For example:
https://www.daft.ie/property-for-rent/dublin returns rental properties in Dublin
https://www.daft.ie/property-for-rent/ireland?location=dublin&location=cork returns properties in Dublin and Cork
https://www.daft.ie/property-for-rent/ireland?location=dublin returns all properties in Ireland **(???)**

Under the rental section:
All properties: https://www.daft.ie/property-for-rent/ireland
Houses: https://www.daft.ie/property-for-rent/ireland/houses
Apartments: https://www.daft.ie/property-for-rent/ireland/apartments
Student accomodations: https://www.daft.ie/student-accommodation-for-rent/ireland **(sneaky special case)**

And special cases go on and on. I can only think of a solution that 
(1) direct users to daft.ie website 
(2) preconfigure their filters
(3) click search and generate the url such as https://www.daft.ie/property-for-rent/ireland/houses?rentalPrice_from=400&rentalPrice_to=17500&numBeds_from=4&numBeds_to=10&leaseLength_from=3
(4) user input the url into this lib
(5) parse the url
(5) this lib automatically scrap the daft website.

**Comment by AnthonyBloomer** [comment]
@YifeiLuDublin I've been looking into how the internal Daft API works and how we can filter data using a JSON payload. I've figured out most things except how to filter by location. This is an example class:

``` python
import requests
from pprint import pprint


class Daft:
    
    def __init__(self):
        self._min_beds = 1
        self._max_beds = 2
        self._min_price = 1500
        self._max_price = 2500
        

    @property
    def min_beds(self):
        return self._min_beds

    @min_beds.setter
    def min_beds(self, min_beds):
        self._min_beds = min_beds

    @property
    def max_beds(self):
        return self._max_beds

    @max_beds.setter
    def max_beds(self, max_beds):
        self._max_beds = max_beds

    @property
    def min_price(self):
        return self._min_price

    @min_price.setter
    def min_price(self, min_price):
        self._min_price = min_price

    @property
    def max_price(self):
        return self._max_price

    @max_price.setter
    def max_price(self, max_price):
        self._max_price = max_price

    def search(self):
        r = requests.post("https://search-gateway.dsch.ie/v1/listings", headers={
            "Content-Type": "application/json",
            "brand": "daft",
            "platform": "web"
        }, json={
            "section": "residential-to-rent",
            "filters":
                [
                    {
                        "name": "adState",
                        "values":
                            [
                                "published"
                            ]
                    },
                    {
                        "values":
                            [
                                "unfurnished"
                            ],
                        "name": "furnishing"
                    }
                ],

            "andFilters":
                [
                    {
                        "values":
                            [
                                "alarm"
                            ],
                        "name": "facilities"
                    }
                ],

            "ranges":
                [
                    {
                        "from": self.min_price,
                        "to": self.max_price,
                        "name": "rentalPrice"
                    },
                    {
                        "from": self.min_beds,
                        "to": self.max_beds,
                        "name": "numBeds"
                    },
                    {
                        "from": "12",
                        "to": "",
                        "name": "leaseLength"
                    }
                ],
            "paging":
                {
                    "from": "0",
                    "pageSize": "20"
                },
            "terms": ""
        }, )
        return r.json()


if __name__ == '__main__':
    daft = Daft()
    daft.min_beds = 1
    daft.max_beds = 2
    daft.min_price = 1500
    daft.max_price = 2000
    listings = daft.search()
    for listing in listings['listings']:
        pprint(listing)
        
```

What I was thinking is that the Daft class would be responsible for building the JSON payload based on what the user sets  which is similar to how this library worked previously except no scraping would be necessary :)

**Comment by YifeiLuDublin** [comment]
> @YifeiLuDublin I've been looking into how the internal Daft API works and how we can filter data using a JSON payload. I've figured out most things except how to filter by location. This is an example class:
> 
> ```python
> import requests
> from pprint import pprint
> 
> 
> class Daft:
>     
>     def __init__(self):
>         self._min_beds = 1
>         self._max_beds = 2
>         self._min_price = 1500
>         self._max_price = 2500
>         
> 
>     @property
>     def min_beds(self):
>         return self._min_beds
> 
>     @min_beds.setter
>     def min_beds(self, min_beds):
>         self._min_beds = min_beds
> 
>     @property
>     def max_beds(self):
>         return self._max_beds
> 
>     @max_beds.setter
>     def max_beds(self, max_beds):
>         self._max_beds = max_beds
> 
>     @property
>     def min_price(self):
>         return self._min_price
> 
>     @min_price.setter
>     def min_price(self, min_price):
>         self._min_price = min_price
> 
>     @property
>     def max_price(self):
>         return self._max_price
> 
>     @max_price.setter
>     def max_price(self, max_price):
>         self._max_price = max_price
> 
>     def search(self):
>         r = requests.post("https://search-gateway.dsch.ie/v1/listings", headers={
>             "Content-Type": "application/json",
>             "brand": "daft",
>             "platform": "web"
>         }, json={
>             "section": "residential-to-rent",
>             "filters":
>                 [
>                     {
>                         "name": "adState",
>                         "values":
>                             [
>                                 "published"
>                             ]
>                     },
>                     {
>                         "values":
>                             [
>                                 "unfurnished"
>                             ],
>                         "name": "furnishing"
>                     }
>                 ],
> 
>             "andFilters":
>                 [
>                     {
>                         "values":
>                             [
>                                 "alarm"
>                             ],
>                         "name": "facilities"
>                     }
>                 ],
> 
>             "ranges":
>                 [
>                     {
>                         "from": self.min_price,
>                         "to": self.max_price,
>                         "name": "rentalPrice"
>                     },
>                     {
>                         "from": self.min_beds,
>                         "to": self.max_beds,
>                         "name": "numBeds"
>                     },
>                     {
>                         "from": "12",
>                         "to": "",
>                         "name": "leaseLength"
>                     }
>                 ],
>             "paging":
>                 {
>                     "from": "0",
>                     "pageSize": "20"
>                 },
>             "terms": ""
>         }, )
>         return r.json()
> 
> 
> if __name__ == '__main__':
>     daft = Daft()
>     daft.min_beds = 1
>     daft.max_beds = 2
>     daft.min_price = 1500
>     daft.max_price = 2000
>     listings = daft.search()
>     for listing in listings['listings']:
>         pprint(listing)
>         
> ```
> 
> What I was thinking is that the Daft class would be responsible for building the JSON payload based on what the user sets which is similar to how this library worked previously except no scraping would be necessary :)

Does that mean this lib will depend on their internal API working? In theory, the internal API shouldn't be exposed.

**Comment by AnthonyBloomer** [comment]
Yeah, this approach would require that we can access their internal API. I think that eventually they may try to block it  especially since Daft.ie don't have a public API offering and only provide the API to their estate agent accounts. 🤑
